### ISSUE TITLE
Hope for wildcards for series of proceedings

### ISSUE THREAD

**Issue by aoyulong** [jlegewie/zotfile#173]
I have installed this plugin and it is wonderful. My major is computer science and the papers I usually read are from proceedings. If I use `%w` as the suffix, the proceedings tile is too long for me. Be honesty, it is hard for me to define my own wildcards. I really hope the new version can add some wildcards for **proceedings abbreviation** or **series of the proceedings**. The following is the sample information of one paper.
![20150331102756](https://cloud.githubusercontent.com/assets/3069790/6911259/b89ad8e4-d790-11e4-8e36-21488a11001c.png)

**Comment by jlegewie** [comment]
There are already so many wildcards so that I recommend that you use a user-defined wildcard. It should be pretty easy for your case but it's still easy to make a mistake. I suggest that you give it a shot and then post on the zotero forum asking for help: https://forums.zotero.org/discussion/5301/24/zotfile-zotero-plugin-to-rename-move-and-attach-pdfs-send-them-to-ipad-extract-pdf-annotations/

**Comment by GrayXu** [comment]
For those who still have this issue   
an example of adding user-defined wildcards for series as %1:  https://github.com/GrayXu/zotfile/commit/217e675db457ae1aa5459629a537d3b1eb33a3aa
[zotfile-series-5.1.1-fx.xpi](https://github.com/GrayXu/zotfile/releases/tag/v5.1.1)
