### ISSUE TITLE
Intrusive dialog on renaming item in multiple collection 

### ISSUE THREAD

**Issue by leoprot** [jlegewie/zotfile#196]
The intrusive dialog on renaming item in multiple collection, asking to choose the main collection to the item is unnecessary. The item maintain its links to all collections, even after you choose one of them.

Without the option to disable this dialog box is impossible make a full batch rename of the attachments.

**Comment by jlegewie** [comment]
There are two hidden options `extensions.zotfile.info_window_duration_clickable` and `extensions.zotfile.info_window_duration` that determine the duration of the dialog window. You can try to change these options to 1 or something. But I am not sure whether I understand your problem entirely and which dialog exactly you are referring to.

**Comment by pterion** [comment]
I think leoprot meant the following dialogue:
![screenshot](https://cloud.githubusercontent.com/assets/15699251/11757649/3c6cc650-a031-11e5-9202-539c4b12ef33.png)
It is very intrusive indeed when renaming a lot of attachments. Is there an option for disabling it and storing the file in the deepest collection subfolder per default? 
Or could you point me to the position in the text where this is defined, so that I could play with it myself.

**Comment by jlegewie** [comment]
This only happens when you use zotero collections to move and rename items. So you can avoid the popup by not using collections to name and move attachments. Zotero items can be in multiple collections so there is no clearly defined location. Any automatic choice (such as "the deepest collection subfolder") is arbitrary and based on personal preference. That is why the dialog is there.

I think(!) the code is in wildcard.js line 365 but I am not 100% sure.
