### ISSUE TITLE
Delete folder(s) if no last file is moved out

### ISSUE THREAD

**Issue by Unode** [jlegewie/zotfile#197]
I frequently store entries with corresponding PDF or other documents before assigning to a given collection. This means they stay in "Unfiled items" and will have a corresponding "undefined/" location on disk.
Later on I reassign the entry to a given collection and hit "Rename attachments" to force the file to move to a new folder matching the new collection. This works fine however the folder hierarchy created under "undefined/..." is, after a while, left full of empty folders.

Could zotfile remove these folders and any parent in the hierarchy when the last file is moved or removed out of it (i.e. when the folder first becomes empty)?

**Comment by Unode** [comment]
Possibly related to #195.

**Comment by jlegewie** [comment]
Yes, that should happen. I actually thought it is the case. So either it's a bug or I removed it at some point because some problem came up. Unfortunately, I won't have time to look into it anytime soon. Let me know you are able and willing to take a look yourself. I can give some more details.

**Comment by Unode** [comment]
Hi Joscha,

I've recently started to rely a bit more on zotfile so I'm finding a few small issues here and there.
If you could give some details would be nice. If I find the time I may look into it along with the other ones.

**Comment by jlegewie** [comment]
For this particular issue, take a look at line 2921 in zotfile.js (see below). Now that I look at it, I think I never implemented the "delete empty folder" feature for renaming. I only did it for removing files from the tablet folder. So you would have to add something similar to the renaming function.

```
// remove subfolder if empty
if(!folder.equals(this.createFile(this.prefs.getCharPref('tablet.dest_dir'))))
    this.removeFile(folder);
```

**Comment by diasalm** [comment]
Hello,
I have been using Zotfile without any trouble for long time, but since a couple of weeks something very strange is happening: every time I use Zotfile to transfer a file from download folder to Zotero folder, it does not delete only the file, but delete the download folder too. So every time I need to save a specific file to download folder I must create it again. Then Zotfile does its job, but it delete download folder after doing it. I have already looked for a fix to this and have also posted this to Zotero foruns but received no answer. I have already tried to reinstall Zotfile after cleaning all Zotfile files from my system. First the fix worked well, but soon the same problem has came back.
Please do you have an idea of what is happening? My settings: I have a Zotero folder in my Dropbox with a mirror in all my laptop/mobile/tablet. In this folder Zotero I have a folder Downloads. So my Zotfile preference for attaching new files is: /home/almd/Dropbox/Zotero/Downloads . And for files location is: /home/almd/Dropbox/Zotero .
Thanks André Mattedi

**Comment by Unode** [comment]
Hi André and Joscha,

It seems the original patch missed one of the copy cases.

[This patch](https://gist.github.com/Unode/cb680eb6568500fed69f) should address the problem.
I didn't have time to test it properly though so please review (carefully) before commiting.

**Comment by diasalm** [comment]
Hi Unode and Joscha,

I'm using Xubuntu and Zotero + Zotfile Firefox add-ons

I've just looked for the file zotfile.js and didnt find it in my system. The only zotfile file I found is zotfile@columbia.edu.xpi ( /home/almd/.mozilla/firefox/06pyuvwb.default/extensions/zotfile@columbia.edu.xpi ).

Best

**Comment by jlegewie** [comment]
Thanks for the patch, Unode! I just looked at it and it makes sense to me. One question: do you think it makes sense to normalize these paths using `OS.Path.normalize`? Could that be relevant for `f.path.startsWith(...` and `f.path !== ...`?

diasalm, I will make the changes on my side and then you can try out whether your problems is fixed. Just finalizing the patch.

**Comment by Unode** [comment]
I do think normalizing makes sense. But to be safe it would have to be done for all paths involved.

Perhaps it could be patched in somewhere else in the code. I.e. normalize every path early so you don't have to worry about it later. I'm not sure which place would be best to patch this in.

**Comment by jlegewie** [comment]
Just made a change based on Unode's patch that should fix the problem. diasalm, can you try and report back? You have to install the version from github based on (these instructions)[https://github.com/jlegewie/zotfile#installation]. Unode, would be great if you also play with the new version.

**Comment by diasalm** [comment]
Hello Joscha and Renato,

It is working well. It is not deleting the Download (source) folder any more. Thanks!
