### ISSUE TITLE
Zotfile incompatible with Zotero 5.0.28

### ISSUE THREAD

**Issue by schignel** [jlegewie/zotfile#323]
I recently updated to Zotero 5.0.28 and it states that Zotfile is no longer compatible. Help, I depend on Zotfile!

**Comment by jlegewie** [comment]
Use zotfile and post support question on the zoetrope forum...

**Comment by GeorgLink** [comment]
@jlegewie what is the link to the zoetrope forum? I cannot find it.

I updated the standalone Zotero to version 5.0.25 on Windows 10 and ZotFile is disabled because incompatible. 
![image](https://user-images.githubusercontent.com/8862021/33378843-cbaf3a24-d4db-11e7-8126-c6ed70588f5a.png)


Maybe this issue could be reopened because making ZotFile compatible with the new Zotero version is a development issue, not a support question.

**Comment by jlegewie** [comment]
Zotero forum. Sorry for that. You have to install zotfile 5 in Zotero 5 NOT firefox.

**Comment by GeorgLink** [comment]
Thanks for the pointer. I didn't realize that I was still using ZotFile 4. After installing the new ZotFile 5, everything works. Sorry for that.

**Comment by schignel** [comment]
Yes I was able to get ZotFile working again by manually downloading it.
