### ISSUE TITLE
Support new URL format for zotero://open-pdf

### ISSUE THREAD

**Issue by dstillman** [jlegewie/zotfile#352]
https://github.com/zotero/zotero/compare/c0a4fa43f...7dbfd5ce adds a zotero://open-pdf handler to Zotero proper, with an updated URL format. It can also read ZotFile URLs, but we'll be generating the new format in Zotero. Since ZotFile will override this handler when installed, it'd be great if the ZotFile handler could be updated to read the new format as well.

More details on the change in https://github.com/zotero/zotero/commit/609657a8e435db9c4d3fcaf96502ac2835e08324, but I think you should be able to just copy [the parsing code](https://github.com/zotero/zotero/blob/60e0d79e01bf83daf8682c0bc088fbeaba496198/components/zotero-protocol-handler.js#L1017-L1049).

The new handler is available for testing in the latest Zotero beta.

**Comment by jlegewie** [comment]
This is great! Is there any reason to not just remove the handler from zotfile considering that you are parsing the old format as well?

I will also see that I update zotfile to the new format.

**Comment by dstillman** [comment]
I think the only reason not to remove the ZotFile handler would be if you wanted the existing ZotFile prefs to keep working. But now that there's a dedicated PDF handler option in the Zotero prefs, there's probably no good reason to keep those.

**Comment by jlegewie** [comment]
I just updated it and will release the new version soon. The handler is still in zotfile but I will remove it in the future.

One question though: Would it be possible to support [PDF Expert](https://pdfexpert.com/) on mac? It should be exactly the same code as `_openWithPreview` [here](https://github.com/zotero/zotero/blob/master/chrome/content/zotero/xpcom/openPDF.js#L131) but with `'PDF Expert'` instead of 'Preview`.

```
await Zotero.Utilities.Internal.exec('/usr/bin/open', ['-a', 'PDF Expert', filePath]);
```

https://github.com/zotero/zotero/blob/master/chrome/content/zotero/xpcom/openPDF.js#L132

**Comment by dstillman** [comment]
Sure — added (untested) in zotero/zotero@e6dbd1ed92213b1f190b4a5de1fb3d06df1b404e

**Comment by jlegewie** [comment]
I just tested it and can confirm that PDF Expert works with Zotero 5.0.48-beta.2 (with zotfile disabled).
