### ISSUE TITLE
renaming to %b no longer works

### ISSUE THREAD

**Issue by annargrs** [jlegewie/zotfile#386]
Not sure whether this is an issue in ZotFile or BetterBibtex, but currently renaming attachments to citation keys no longer works (used to be pattern %b). Renaming to other patterns works.

Zotero 5.0.60 on Ubuntu, ZotFile 5.0.9, Better Bibtex 5.1.40.

**Comment by retorquere** [comment]
I used to monkey-patch ZotFile in the BBT 4.x series but in the 5 series I dropped the live patching, and ZotFile has changed enough so that I can't easily find where I'd have to add it (and I'd also strongly prefer to bring down the number of monkey patches BBT does).

It'd be fairly easy for ZotFile to grab the BBT citekey though; given an `itemID`, this will do it:

```
const citekey = Zotero.BetterBibTeX ? (Zotero.BetterBibTeX.KeyManager.get(itemID) || {}).citekey : undefined
```

which will get you either the citekey or `undefined` if it can't be found.

**Comment by rcoreilly** [comment]
Please fix! :). This is an essential part of our lab's workflow -- really appreciate these tools working together so that the PDF's can be renamed and thus linked directly to the corresponding entry in our large Zotero database.

**Comment by jlegewie** [comment]
@retorquere was this ever part of zotfile or did you add %b with a monkey patch?

Is this still the right line of code to get the bibtex key? Is it possible to get the key from Zotero if BetterBibTeX is not installed (to replace the `undefined` in the line of code)?

```
const citekey = Zotero.BetterBibTeX ? (Zotero.BetterBibTeX.KeyManager.get(itemID) || {}).citekey : undefined
```

**Comment by retorquere** [comment]
I added it with a monkey-patch.

That code should work, but I just thought that the following would also work, and does look simpler to me (if you happen to have the `item` handy):

```
try {
  return item.getField('citekey')
} catch (err) {
  return ''
}
```

The try-catch is needed because if BBT is not installed, the request for `'citekey'` is invalid, and Zotero will throw an error.

**Comment by jlegewie** [comment]
I just pushed a commit that should add the `%b` wildcard. Can anyone install the GitHub version, try and confirm here? I will publish the new version after I get confirmation that it works.

**Comment by annargrs** [comment]
Sorry, I couldn't figure out how the repo turns to an installable extension. Are there any instructions for that? I'm happy to test.

**Comment by jlegewie** [comment]
That was supposed to be a thumbs up...  :)

**Comment by rcoreilly** [comment]
here's a belated yet sincere thanks in fixing this!! :)
