### ISSUE TITLE
Removing HTML tags completely when renaming files

### ISSUE THREAD

**Issue by stefanct** [jlegewie/zotfile#455]
I had to add some HTML tags into a title to make the BBT export work as intended (cf. https://github.com/retorquere/zotero-better-bibtex/issues/1410). While that works fine and does not break the renaming of zotfile it creates quite ugly filenames. For example, I am using `{%y-}{%a-}{%t}` as the format and thus a the title `V0LTpwn: attacking <span class="nocase">x86</span> <b>processor</b> integrity from software` renames the respective PDF to `2019-Kenjar-V0LTpwn_-_attacking_span_class=nocasex86-span_bprocessor-b_integrity.pdf`, which is arguably even worse than the original.

Should this be handled by Zotero itself (it's gui shows the whole markup everywhere as well) or can we get improved code for that in zotfile (apparently there is filtering of `<` and `>` in place already)?

**Comment by retorquere** [comment]
Just a minor point - the markup isn't there to make BBT work as intended, BBT works as intended by rendering that markup (which is just the zotero way to express the intent "don't change case when rendering a bibliography" - this is not BBTs design choice) to latex. Zotero supports more of this html-ish markup, and BBT just translates the intent that markup expresses to corresponding latex.

**Comment by qqobb** [comment]
Zotfile's <a href="https://github.com/jlegewie/zotfile/blob/master/docs/index.md#user-defined-wildcards">user-defined wildcards</a> could serve as a workaround here.

E.g., for the title `V0LTpwn: attacking <span class="nocase">x86</span> <b>processor</b> integrity from software`, this wildcard might do what you want:

`{"1": {"field": "title", "operations":[{"function": "replace", "regex": "<span class=.nocase.>", "replacement":"", "flags":"g"},{"function": "replace", "regex": "</span>", "replacement":"", "flags":"g"},{"function": "replace", "regex": "<b>", "replacement":"", "flags":"g"},{"function": "replace", "regex": "</b>", "replacement":"", "flags":"g"}]}}`

(Setting through "Zotero Preferences" -> "Advanced" -> "General" -> "Config Editor" -> "extensions.zotfile.wildcards.user")

I don't know how to make a user wildcard with a more general regex like `<("[^"]*"|'[^']*'|[^'">])*>` [1] or `<(?:"[^"]*"['"]*|'[^']*'['"]*|[^'">])+>` [2]. (The double quotes might be problematic for the JSON form. You could check Zotfile's [wildcards.js](https://github.com/jlegewie/zotfile/blob/master/chrome/content/zotfile/wildcards.js)) But I'm not sure a more general regex would be an improvement in this case, since it might fail on a title like `Check that 1<2 with a <span class="nocase">x86</span> <b>processor</b>`, as you could check using an online tool [3]. If the number of HTML tags used for Zotero titles is small, you could easily adapt the wildcard above. Clearly, the proper way would be some HTML parsing. But this should be more relevant for Zotero's UI.

BTW, I'm not saving HTML tags in Zotero's title fields since I don't need them for Word/LibreOffice. I use wildcards like `{"1": {"field": "titleFormated", "operations":[{"function": "replace", "regex": "[\\u2010-\\u2015\\u002D\\u2212\\uFE58\\uFE63\\uFF0D]", "replacement": "-", "flags":"g"},{"function": "replace", "regex": "[ξ]", "replacement":"xi", "flags":"g"}]}}`, where the first part replaces various dashes with a minus character, as my BibTeX program couldn't open files with such characters in their name.

LaTeX markup in Zotero's title fields can give rise to the same readability issue as with HTML tags. My solution is to save Zotero's "Title" fields without any markup, while saving titles with LaTeX markup in Zotero's "Short Title" field, protecting this in BBT exports using a <a href="https://github.com/retorquere/zotero-better-bibtex/blob/master/site/content/exporting/scripting.md#detect-and-protect-latex-math-formulas">BBT postscript</a>. One might be able to do something similar with HTML markup. Hopefully, Zotero will have some better way of dealing with this in the future, e.g., using custom fields. <a href="https://github.com/Juris-M/zotero">Juris-M</a> might have some related functions already, but probably not specifically for markup in titles.

[1] Friedl, Mastering regular expressions (3rd ed., 2006), ISBN 978-0-596-52812-6, p. 200
[2] https://stackoverflow.com/a/1736801
[3] https://regex101.com

**Comment by stefanct** [comment]
Thanks a lot for your suggestions. I was trying to add that `wildcards.user` workaround but it does not seem to work. I don't understand why though. The only related debut output I get is:

    (3)(+0000015): Filename has not changed
    (4)(+0000002): Item 207 has not changed

The functions in that operations list are independent, right? Any ideas?

**Comment by qqobb** [comment]
You might have forgotten to actually use the wildcard. If you're using `{%y-}{%a-}{%t}`, you should now use `{%y-}{%a-}{%1}` instead.

The more general regex actually works when using the unicode code point for the quotation marks:
`{"1": {"field": "title", "operations":[{"function": "replace", "regex": "<(\\u0022[^\\u0022]*\\u0022|'[^']*'|[^'\\u0022>])*>", "replacement":"", "flags":"g"}]}}`.

You could add something like `{"function": "exec", "regex": "([\\w ,-]{1,50})[:\\.?!]?", "group":1, "flags":"g"}` to the operations. Note that some of Zotfile's renaming preferences only have effect on the `titleFormated` field. Please check [wildcards.js](https://github.com/jlegewie/zotfile/blob/master/chrome/content/zotfile/wildcards.js) for more details.

BTW, a related Zotero issue is e.g. https://github.com/zotero/zotero/issues/81.

**Comment by stefanct** [comment]
*facepalm* Yes, it's working, thanks.

I am not entirely sure why you propose the second function though (how is it related to my question). AFAICT that would limit the names to the first 50 characters before a colon or end of a sentence? Am I correct in assuming that this would not fail because of duplicate filenames, i.e. that a suitable suffix is still appended to make it unique if need be?

**Comment by qqobb** [comment]
For using regular expressions to filter out HTML tags, you need to use the `title` field instead of the `titleFormated` field. However, your settings for, e.g., shortening the file names in the "ZotFile Preferences..." window only apply to the `titleFormated` field. Therefore, you might get very long file names for Zotero items with very long titles if you would only remove HTML tags with the first regular expression. (Test this, e.g., with adding text to your sample title.) If you don't want this, you could add the second renaming rule to the operations:
`{"1": {"field": "title", "operations":[{"function": "replace", "regex": "<(\\u0022[^\\u0022]*\\u0022|'[^']*'|[^'\\u0022>])*>", "replacement":""},{"function": "exec", "regex": "([\\w ,-]{1,50})[:\\.?!]?", "group":1}]}}`
(Test this, e.g., also with removing `:` from your sample title.)

The `titleFormated` field has some additional beautification measures, e.g., for not cutting the title in the middle of a word. I created a pull request (#458) that would allow you to keep using these preferences and beautification when using regular expressions to remove HTML tags. With the changes in the PR, you could use this:
`{"1": {"field": "title", "operations":[{"function": "replace", "regex": "<(\\u0022[^\\u0022]*\\u0022|'[^']*'|[^'\\u0022>])*>", "replacement":""},{"function": "truncateTitle"}]}}`

Generally, I would recommend to make some quick tests to see if you're happy with the results.

**Comment by qqobb** [comment]
@stefanct: If you want to try this, follow the [installation instructions](https://github.com/jlegewie/zotfile#installation) for the development version. You could also replace `wildcards.js` in the `zotfile-5.0.16-fx.xpi` with the master branch version.

**Comment by stefanct** [comment]
I am still a bit confused TBH. I don't care about the length of the file names at all (quite the opposite: I would not like them to be mangled :) Thus I have the respective option disabled anyway.

**Comment by qqobb** [comment]
Not sure what's causing the confusion. If you don't care about the file name length, just use the first regex.

**Comment by stefanct** [comment]
I was not sure about the continuous activity and prompts in this issue. I am satisfied with the first workaround for now, yes, till Zotero is improved. Thanks!

**Comment by stefanct** [comment]
The dash replacements you mentioned initially are very useful as well (many titles have an em-dash). I have added that to my user regex but I think that it would make sense for other ppl as well, i.e., I propose to have that as an option in the GUI.

**Comment by stefanct** [comment]
I have added quite a bunch of Diacritics and Umlauts etc. to my author conversions and some more for title.
Just in case somebody may find that useful, here is my current setup:

    {
      "1":{
        "default":{
          "field": "author", "operations":[ {
              "function": "replace", "regex": "[ä]", "replacement":"ae", "flags":"g"
            }, {
              "function": "replace", "regex": "[ö]", "replacement":"oe", "flags":"g"
            }, {
              "function": "replace", "regex": "[ü]", "replacement":"ue", "flags":"g"
            }, {
              "function": "replace", "regex": "[Ä]", "replacement":"Ae", "flags":"g"
            }, {
              "function": "replace", "regex": "[Ö]", "replacement":"Oe", "flags":"g"
            }, {
              "function": "replace", "regex": "[Ü]", "replacement":"Ue", "flags":"g"
            }, {
              "function": "replace", "regex": "[ćĉčċḉƈȼçꞔꞓ]", "replacement":"c", "flags":"g"
            }, {
              "function": "replace", "regex": "[ĆĈČĊḈƇȻÇꞒ]", "replacement":"C", "flags":"g"
            }, {
              "function": "replace", "regex": "[śṡṩṥṣs̩ꞩŝṦṧšşșs̈ᶊȿ]", "replacement":"s", "flags":"g"
            }, {
              "function": "replace", "regex": "[ŚṠṨṤṢS̩ꞨŜṦŠŞȘ̈Ȿ]", "replacement":"S", "flags":"g"
            }, {
              "function": "replace", "regex": "[ţťŧƫƭʈțṫṭṯṱ̈ẗ́t́]", "replacement":"t", "flags":"g"
            }, {
              "function": "replace", "regex": "[ŢŤŦƬƮȚṪṬṮṰT̈T́]", "replacement":"T", "flags":"g"
            }, {
              "function": "replace", "regex": "[źẑžżẓẕƶᵶᶎⱬ]", "replacement":"z", "flags":"g"
            }, {
              "function": "replace", "regex": "[ŹẐŽŻẒẔƵⱫ]", "replacement":"Z", "flags":"g"
            }, {
              "function": "replace", "regex": "[ẞ]", "replacement":"Sz", "flags":"g"
            }, {
              "function": "replace", "regex": "[ſß]", "replacement":"sz", "flags":"g"
            }
          ]
        }
      },
      "2":{
        "default":{
          "field": "title", "operations":[
            {
              "function": "replace", "regex": "<(\\u0022[^\\u0022]*\\u0022|'[^']*'|[^'\\u0022>])*>", "replacement": "", "flags":"g"
            }, {
              "function": "replace", "regex": "[\\u2010-\\u2015\\u002D\\u2212\\uFE58\\uFE63\\uFF0D]", "replacement": "-", "flags":"g"
            }, {
              "function": "replace", "regex": "[μµⲙ]", "replacement": "u", "flags":"g"
            }, {
              "function": "replace", "regex": "[ΜⲘ]", "replacement": "U", "flags":"g"
            }, {
              "function": "replace", "regex": "[δ𝛿]", "replacement":"delta", "flags":"g"
            }, {
              "function": "replace", "regex": "[Δ∆]", "replacement":"Delta", "flags":"g"
            }
          ]
        }
      }
    }

**Comment by qqobb** [comment]
@stefanct: Your wildcard's
```
          "function": "replace", "regex": "[śṡṩṥṣs̩ꞩŝṦṧšşșs̈ᶊȿ]", "replacement":"s", "flags":"g"
          "function": "replace", "regex": "[ŚṠṨṤṢS̩ꞨŜṦŠŞȘ̈Ȿ]", "replacement":"S", "flags":"g"
          "function": "replace", "regex": "[ţťŧƫƭʈțṫṭṯṱ̈ẗ́t́]", "replacement":"t", "flags":"g"
          "function": "replace", "regex": "[ŢŤŦƬƮȚṪṬṮṰT̈T́]", "replacement":"T", "flags":"g"
```
seems to be inspired by https://stackoverflow.com/a/1732454 :-)

<p><b>O​O N</b>Θ stop t<i>he an​*̶͑̾̾​̅ͫ͏̙̤g͇̫͛͆̾ͫ̑͆l͖͉̗̩̳̟̍ͫͥͨ</i>e̠̅s<code> ͎a̧͈͖r̽̾̈́͒͑e</code> n<b>​ot rè̑ͧ̌aͨl̘̝̙̃ͤ͂̾̆ ZA̡͊͠͝LGΌ ISͮ̂҉̯͈͕̹̘̱ T</b>O͇̹̺ͅƝ̴ȳ̳ TH̘<b>Ë͖́̉ ͠P̯͍̭O̚​N̐Y̡ H̸̡̪̯ͨ͊̽̅̾̎Ȩ̬̩̾͛ͪ̈́̀́͘ ̶̧̨̱̹̭̯ͧ̾ͬC̷̙̲̝͖ͭ̏ͥͮ͟Oͮ͏̮̪̝͍M̲̖͊̒ͪͩͬ̚̚͜Ȇ̴̟̟͙̞ͩ͌͝</b>S̨̥̫͎̭ͯ̿̔̀ͅ</p>
