### ISSUE TITLE
'convert linked files to stored files' option grayed out

### ISSUE THREAD

**Issue by felixhelix** [jlegewie/zotfile#459]
Hi, 
I cannot convert my attachments to stored files: the option 'manage attachnents/'convert linked files to stored files' is grayed out.
Any ideas what can prevent this from working?
I'm using zotero 5.0.82 with zotfile 5.0.16 on Ubuntu 18.04.4.
Thanks,
Felix

**Comment by qqobb** [comment]
In view of <a href="https://forums.zotero.org/discussion/comment/308570/#Comment_308570">this comment</a> from the Zotfile developer, it might generally be better to ask for help on the Zotero forum. Github issues might still be appropriate for some technical matters, but you shouldn't expect an answer.

What you describe isn't a Zotfile issue, since the function "Convert Linked Files to Stored Files" is part of the main Zotero app. If the option is only grayed out for items in the trash, you could comment <a href="https://forums.zotero.org/discussion/comment/344296/#Comment_344296">here</a>. Otherwise, I would suggest to start a new discussion on the Zotero forum.

**Comment by felixhelix** [comment]
Thanks for your comment! I will have a look at the Zotero forum.
