### ISSUE TITLE
Zotfile BUG

### ISSUE THREAD

**Issue by MartinYuan1995** [jlegewie/zotfile#501]
Hi, it is useless when I click Zotfile plugin in the tools list after Zotero running for a long time. But every time I restart Zotero, the plugin can be opened successfully. 
![55A3E9917A6B5E80BD893B283C5AE339](https://user-images.githubusercontent.com/47047658/104154865-df7b0480-5420-11eb-999d-b02e4756e8bb.jpg)

**Comment by MartinYuan1995** [comment]
does anyone can help me?

**Comment by NanonaN** [comment]
I am experiencing the same issue. My workaround is to restart zotero everytime zotfile stops working, somehow annoying indeed.

**Comment by ahrendsen** [comment]
This sounds like it could be a Zotero issue rather than a ZotFile issue. Could you both provide more information about your systems? 
What versions of Zotero are you running? (Help>About Zotero>The numbers just below "Zotero" in the pane that pops up) What versions of ZotFile are you running? (Tools>Add ons> "More" under ZotFile> The numbers after "ZotFile"

Full disclosure, I'm not a developer, just trying to help out and diagnose the problem.

Karl

**Comment by ahrendsen** [comment]
Were you able to resolve the issue?

**Comment by MartinYuan1995** [comment]
> Were you able to resolve the issue?

Hi, this problem still exists. And I submit my problem in the Zotero forum, somebody says it seems BUG of Zotero.  Now, when I need to close Zotero, I will quit it totally. 
Thank you for helping Me, and how to delete my issue?

**Comment by ahrendsen** [comment]
That's great to hear that someone else was able to help you better understand the problem. We should keep the issue here rather than deleting it. That way if any other users experience the same problem, they can learn from your experiences.
