### ISSUE TITLE
i cant extract annotations anymore

### ISSUE THREAD

**Issue by tjallemaal** [jlegewie/zotfile#508]
![Screenshot 2021-02-03 at 15 36 24](https://user-images.githubusercontent.com/69585777/106762399-16b28f00-6636-11eb-9ae2-eb9e43f59d7b.png)

**Comment by qqobb** [comment]
@tjallemaal: I'm just posting this because it might be helpful to others.

```
Zotfile: Extracting Annotations…

Attachments skipped because they are top-level items, snapshots or the file does not exist.
```

It seems @tjallemaal was able to resolve this issue after resetting invalid user-defined wildcards, see here:
https://forums.zotero.org/discussion/87430/zotfile-extract-annotations-does-not-work-mc-os

Usage questions should generally go to the [Zotero forums](https://forums.zotero.org/).

If you start a new discussion there, be sure to include "ZotFile" in the thread title.
