### ISSUE TITLE
How to get address of the pdf file moved by Zotfile?

### ISSUE THREAD

**Issue by linjunhe** [jlegewie/zotfile#547]
The pdf files 
- are accessible by 
`[this is a pdf.pdf](zotero://select/library/items/8WF36G3B)` 
- and can be opened by `[this is a pdf.pdf](zotero://open-pdf/library/items/8WF36G3B)`.

If the pdf files are managed by Zotfile, (that is, they are not in “`Zotero/Storage/8WF36G3B`”, but are moved to another folder. The above two links are still available.

However, are there any methods that we can get the new folder address for each pdf file according to “`8WF36G3B`”? 

For example, if we are making a plugin that needs the new address of the pdf file, how can we do it?

**Comment by jlegewie** [comment]
Not sure what you mean. The path of pdf files is still accessible through the Zotero API when they are moved by zotfile. Only exception is  when you move a file to the tablet in "background" mode, which create a copy of the file (so there are two version). But otherwise, the Zotero API will give you the correct path.
