### ISSUE TITLE
Windows zotero 6.0 beta can't seem to use the Extract Annotation feature of zotfile

### ISSUE THREAD

**Issue by ydivho12123** [jlegewie/zotfile#586]
Windows zotero 6.0 beta can't seem to use the Extract Annotation feature of zotfile

**Comment by Mickychen00** [comment]
I also have some question

**Comment by Mickychen00** [comment]
I have have same question.

**Comment by wd-77** [comment]
I have have same question.

**Comment by longqq2** [comment]
I have have same question.

**Comment by fcg-bio** [comment]
Same to me using the v5.1.0 in Zotero 6.0-beta.11+121f3f303 version in **Mac**

**Comment by jlegewie** [comment]
Zotero 6 integrates the function to extract annotations. No need to use zotfile for that anymore. Try this: Right click on item (not the attachment) and select "Add Note from Annotations".

I have not tested this in detail but Zotero's function should work better because it is based on a more recent version of pdf.js.

**Comment by mirenbz** [comment]
Thanks for that @jlegewie ! I was beginning to mourn the loss of annotation extraction already. Made my day :)
