### ISSUE TITLE
extract annotations not avalable on new Zotero 6.0

### ISSUE THREAD

**Issue by janwyler** [jlegewie/zotfile#589]
I updated my Zotero version and now the extraction of pdf annotations with zotfile doesn't work anymore. It would be great to have it also in Zotero 6.0.

**Comment by jlegewie** [comment]
Zotero 6 integrates the function to extract annotations. No need to use zotfile for that anymore. Try this: Right click on item (not attachment) and select "Add Note from Annotations".

I have not tested this in detail but Zotero's function should work much better because it is based on a much more recent version of pdf.js.
